version: '3.7'
services:

  postgres:
    image: postgres:14-alpine
    ports:
      - '5434:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user_login
      - POSTGRES_PASSWORD=mREsvXDs9Gk89Ef